### ISSUE TITLE
Commit 정책 결정

### ISSUE THREAD

**Issue by hochan222** [42js/you-dont-know-js-yet#1]
🥇 Commit Message 정책을 정해봐요.

앞에 문구 종류: https://blog.ull.im/engineering/2019/03/10/logs-on-git.html
좋은 git 커밋 메시지를 작성하기 위한 8가지 약속: https://djkeh.github.io/articles/How-to-write-a-git-commit-message-kor/
Commit Message 바꾸기: http://tech.javacafe.io/2018/03/01/how-to-change-git-commit-message/

<정책>

커밋은 다음과 같은 형식으로 지정한다.
[커밋 종류]: 파일명 / 내용 (Pull requests 번호 링크)

- 커밋 종류

[FIX]: 파일명 / 내용 (Pull requests 번호)
Description: 코드 버그 수정

[CREATE]: 파일명 / 내용 (Pull requests 번호)
Description: 코드파일, 디렉토리 생성

[COMPLETE]: 파일명 / 내용 (Pull requests 번호)
Description: 더이상 추가사항 없을시

[REMOVE]: 파일명 / 내용 (Pull requests 번호)
Description: 불필요한 파일, 디렉토리 제거

[REFACTOR]: 파일명 / 내용 (Pull requests 번호)
Description: [FIX], 불필요한 주석 제거, 간소화

**Comment by cos18** [comment]
저는 이 링크에 적혀있는 커밋 메세지 규칙을 지키는데, 위 내용도 나쁘진 않을 것 같아요!

http://karma-runner.github.io/5.2/dev/git-commit-msg.html

**Comment by hochan222** [comment]
오오!! 주신 링크 좋은것같아요! 좀 더 명확히 나눠져있는것 같습니댜. 제껀 앞에 [] 감싸는것만 가져오고 나머지는 링크대로 하면 어떤가요?

**Comment by cos18** [comment]
> 오오!! 주신 링크 좋은것같아요! 좀 더 명확히 나눠져있는것 같습니댜. 제껀 앞에 [] 감싸는것만 가져오고 나머지는 링크대로 하면 어떤가요?

그러면 기준은 제가 올린 링크로, 형태는 "[feat] add somethihg" 요런식으로 할까요?

**Comment by hochan222** [comment]
> 그러면 기준은 제가 올린 링크로, 형태는 "[feat] add somethihg" 요런식으로 할까요?

네! 좋아요! 대문자가 조금 더 멋있는데 [FEAT]은 어떤가요?

**Comment by cos18** [comment]
전 상관없을 것 같습니다. 대문자로 하죠!
