### ISSUE TITLE
[Get Started] Practice Part 2

### ISSUE THREAD

**Issue by cos18** [42js/you-dont-know-js-yet#4]
You Don't Know JS Yet - Get Started 에 수록되어 있는 Practice 문제들을 다음 스터디 하루 전까지 풀어야 합니다.
PR에 올라가면 다른 스터디원들에게 코드 리뷰를 받을 예정입니다.

### 문제 항목
- [Practicing Closure](https://github.com/getify/You-Dont-Know-JS/blob/2nd-ed/get-started/apB.md#practicing-closure)
- [Practicing Prototypes](https://github.com/getify/You-Dont-Know-JS/blob/2nd-ed/get-started/apB.md#practicing-prototypes)

### 마감 기한
**2020-12-30 23:59**

### 주의사항
- Commit Message 정책 (#1) 을 지켜주세요.
- 브랜치명은 `practice/sunpark`와 같이 `practice/(intra id)`의 형식으로 이름을 지어주세요. 이후 다른 프랙티스 문제를 풀 때도 사용함으로 머지할 때 브랜치를 지우지 말아주세요.
- PR의 Reviewers는 본인을 제외한 6명을 지정해주세요. 지정해주셔야 다른 스터디원이 코드를 리뷰할 수 있습니다.
- PR에 "practice" 라벨을 달아주세요.

**Comment by hochan222** [comment]
```About issue [#4](https://github.com/42js/you-dont-know-js-yet/issues/4)```
풀리퀘에서 위와 같이 issue link로 언급해주면 issue에서 아래 사진과 같이 멘션 할 수 있습니다!

![image](https://user-images.githubusercontent.com/22424891/103288485-4f07f180-4a28-11eb-9028-a61f83fc9091.png)
